server:
  port: 8080
---
spring:
  application:
    name: miniautorizador
  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    hikari:
      read-only: false
  jpa:
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: miniautorizador
        type: trace
---
logging:
  level:
    root: info
    org.hibernate.SQL: debug
---