server:
  port: 8080
---
spring:
  application:
    name: miniautorizador
  datasource:
    url: jdbc:h2:file:./h2/miniautorizador;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS miniautorizador
    driver-class-name: org.h2.Driver
    username: root
    password:
    hikari:
      read-only: false
  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: miniautorizador
        type: trace
---
logging:
  level:
    root: info
    org.hibernate.SQL: debug
---